version: 2.1
description: "Sonatype Nexus Platform Integration"

executors:
  default:
    description: "CircleCI image for OpenJDK"
    docker:
    - image: circleci/openjdk

commands:
  install:
    description: "Installs the nexus-platform-api and CLI script"
    parameters:
      groovy-version:
        type: string
        default: "2.5.3"
    steps:
    # TODO: when NexusPublisher.groovy script has a released version update the curl command below accordingly
    - run: |
        curl -L https://dl.bintray.com/groovy/maven/apache-groovy-binary-<<parameters.groovy-version>>.zip -o apache-groovy-binary.zip
        curl -L https://raw.githubusercontent.com/sonatype-nexus-community/circleci-nexus-orb/INT-1109_repository_groovy_wrapper/cli/src/main/groovy/NexusPublisher.groovy -o NexusPublisher.groovy
        unzip apache-groovy-binary.zip
        mv groovy-<<parameters.groovy-version>> groovy

  archive:
    description: "Archives artifacts to Nexus Repository Manager"
    parameters:
      username:
        description: "Username to access Nexus Repository Manager"
        type: string
        default: "${NEXUS_RM_USERNAME}"
      password:
        type: string
        default: "${NEXUS_RM_PASSWORD}"
      serverurl:
        type: string
        default: "${NEXUS_RM_SERVERURL}"
      filename:
        type: string
      format:
        type: string
        default: "maven2"
      params:
        type: string
      repository:
        type: string
        default: "maven-releases"

    steps:
    - attach_workspace:
        at: /tmp/workspace
    - run: >
        groovy/bin/groovy NexusPublisher.groovy
        --username <<parameters.username>>
        --password <<parameters.password>>
        --serverurl <<parameters.serverurl>>
        --filename <<parameters.filename>>
        --format <<parameters.format>>
        --repository <<parameters.repository>>
        <<parameters.params>>

jobs:
  nexusjob:
    description: "Publish artifacts to Nexus Respository Manager"
    parameters:
      username:
        description: "Username to access Nexus Repository Manager"
        type: string
        default: "${NEXUS_RM_USERNAME}"
      password:
        type: string
        default: "${NEXUS_RM_PASSWORD}"
      serverurl:
        type: string
        default: "${NEXUS_RM_SERVERURL}"
      filename:
        type: string
      format:
        type: string
        default: "maven2"
      params:
        type: string
      repository:
        type: string
        default: "maven-releases"
      groovy-version:
        type: string
        default: "2.5.3"
    executor: default
    steps:
    - install:
      groovy-version: << parameters.groovy-version >>
    - archive:
        username: << parameters.username >>
        password: << parameters.password >>
        serverurl: << parameters.serverurl >>
        filename:  << parameters.filename >>
        format: << parameters.format >>
        params: << parameters.params >>
        repository: << parameters.repository >>
