version: 2.1
description: >
  Sonatype Nexus Platform Integration. This Orb allows publishing of build
  artifacts to Nexus Repository Manager instances. The source for this Orb is
  available at: https://github.com/sonatype-nexus-community/circleci-nexus-orb

executors:
  nexus-platform-cli:
    description: "Sonatype image with Nexus Platform CLI"
    docker:
    - image: sonatype/nexus-platform-cli:0.0.20190221-200155.19a5dd0

commands:
  install:
    description: "Installs the nexus-platform-api and CLI script"
    parameters:
      groovy-version:
        description: "Version of Apache groovy to download and install"
        type: string
        default: "2.5.3"
      script-version:
        description: "Version of NexusPublisher groovy script to download and install."
        type: string
        default: "master"
      sonatypedir:
        description: "Location of Sonatype scripts"
        type: string
        default: "${CIRCLE_WORKING_DIRECTORY}/sonatype"
    steps:
    - run: |
        curl -L https://dl.bintray.com/groovy/maven/apache-groovy-binary-<< parameters.groovy-version >>.zip -o apache-groovy-binary.zip
        mkdir -p << parameters.sonatypedir >>/bin || true
        curl -L https://raw.githubusercontent.com/sonatype-nexus-community/docker-nexus-platform-cli/<< parameters.script-version >>/src/main/groovy/NexusPublisher.groovy -o << parameters.sonatypedir >>/bin/NexusPublisher.groovy
        unzip apache-groovy-binary.zip
        mv groovy-<< parameters.groovy-version >> groovy
        echo PATH=${PATH}:${CIRCLE_WORKING_DIRECTORY}/groovy/bin/ > setup.sh

  publish:
    description: "Publishes artifacts to Nexus Repository Manager"
    parameters:
      username:
        description: "Username to access Nexus Repository Manager"
        type: string
        default: "${NEXUS_RM_USERNAME}"
      password:
        description: "Password to access Nexus Repository Manager"
        type: string
        default: "${NEXUS_RM_PASSWORD}"
      serverurl:
        description: "Nexus Repository Manager Server URL"
        type: string
        default: "${NEXUS_RM_SERVERURL}"
      filename:
        description: "Path of file to publish"
        type: string
      format:
        description: "Format of artifact to publish"
        type: string
        default: "maven2"
      attributes:
        description: "Component coordinates and Asset attributes"
        type: string
      repository:
        description: "Target repository name"
        type: string
        default: "maven-releases"
      workspace:
        description: "CircleCI workspace attachment point"
        type: string
        default: ""
      sonatypedir:
        description: "Location of Sonatype scripts"
        type: string
        default: "${CIRCLE_WORKING_DIRECTORY}/sonatype"
    steps:
    - when:
        condition: << parameters.workspace >>
        steps:
          - attach_workspace:
              at: << parameters.workspace >>
    - run: >
        [[ -r setup.sh ]] && . setup.sh ;
        groovy << parameters.sonatypedir >>/bin/NexusPublisher.groovy
        --username << parameters.username >>
        --password << parameters.password >>
        --serverurl << parameters.serverurl >>
        --filename $(if [ ! -z "<< parameters.workspace >>" ] ; then echo << parameters.workspace >>/ ; fi)<< parameters.filename >>
        --format << parameters.format >>
        --repository << parameters.repository >>
        << parameters.attributes >>

jobs:
  nexusjob:
    description: "Publish artifacts to Nexus Respository Manager"
    parameters:
      username:
        description: "Username to access Nexus Repository Manager"
        type: string
        default: "${NEXUS_RM_USERNAME}"
      password:
        description: "Password to access Nexus Repository Manager"
        type: string
        default: "${NEXUS_RM_PASSWORD}"
      serverurl:
        description: "Nexus Repository Manager Server URL"
        type: string
        default: "${NEXUS_RM_SERVERURL}"
      filename:
        description: "Path of file to publish"
        type: string
        default: "${NEXUS_RM_FILENAME}"
      format:
        description: "Format of artifact to publish"
        type: string
        default: "maven2"
      attributes:
        description: "Component coordinates and Asset attributes"
        type: string
        default: "${NEXUS_RM_ATTRIBUTES}"
      repository:
        description: "Target repository name"
        type: string
        default: "maven-releases"
      workspace:
        description: "CircleCI workspace attachment point"
        type: string
        default: "/tmp/workspace"
      sonatypedir:
        description: "Location of Sonatype scripts"
        type: string
        default: "/opt/sonatype"
    executor: nexus-platform-cli
    steps:
    - publish:
        username: << parameters.username >>
        password: << parameters.password >>
        serverurl: << parameters.serverurl >>
        filename:  << parameters.filename >>
        format: << parameters.format >>
        attributes: << parameters.attributes >>
        repository: << parameters.repository >>
        workspace: << parameters.workspace >>
        sonatypedir: << parameters.sonatypedir >>
